name: Check CMake version matches tag

on:
  push:
    tags:
      'v*'
    branches: 
        - develop
        - patch/*
        - prep-release/*
    paths-ignore:
        - 'docs/**'
        - '.github/**'
  pull_request:
    branches: [ develop ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG=$LATEST_TAG"
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Extract version from CMakeLists.txt
        id: extracted_tag
        run: |
          CMAKE_VERSION=$(grep -Po 'project\([^)]*VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "CMAKE_VERSION=$CMAKE_VERSION"
          echo "CMAKE_VERSION=${CMAKE_VERSION}" >> $GITHUB_ENV

      - name: Check version against tag
        run: |
          TAG_VERSION=${LATEST_TAG#v}
          echo "Comparing latest tag: $TAG_VERSION to the CMakeLists.txt version: $CMAKE_VERSION
          if [[ "$TAG_VERSION" != "$CMAKE_VERSION" ]]; then
            echo "ERROR: Version mismatch! Latest tag is $TAG_VERSION but CMakeLists.txt has $CMAKE_VERSION"
            exit 1
          fi

