name: Schedule trigger test (temp)

# This workflow is for testing purposes only. If you're reading this in April
# 2026 or later, contact Andrew Mogan and remind him to delete this.
on:
  schedule:
    - cron: "40 14 * * *"

  workflow_dispatch:

jobs:
  build_develop_dispatch:
    name: Schedule action on feature branch
    uses: DUNE-DAQ/.github/.github/workflows/dunedaq-develop-cpp-ci.yml@amogan/single_package_linting
    with:
      caller_event_name: ${{ github.event_name }}